#ifndef RAYCASTING_CONFIG_H
#define RAYCASTING_CONFIG_H

#define PROGRAM_NAME "Raycasting"

#define FONT_PATH "assets/fonts/Px437_IBM_VGA_8x16.ttf"

#define GLYPH_WIDTH 8
#define GLYPH_HEIGHT 16

#define RENDER_WIDTH 120
#define RENDER_HEIGHT 33

#define PRESENT_WIDTH (GLYPH_WIDTH * RENDER_WIDTH)
#define PRESENT_HEIGHT (GLYPH_HEIGHT * RENDER_HEIGHT)

#endif //RAYCASTING_CONFIG_H
